#!/bin/sh
#timezone
uci set system.@system[0].timezone='CST-8'
uci set system.@system[0].zonename='Asia/Shanghai'
uci commit system
#feed
sed -i '/openwrt_luci/ { s/snapshots\/packages/releases\/packages-19.07/g; }'      /etc/opkg/distfeeds.conf
sed -i '/openwrt_packages/ { s/snapshots\/packages/releases\/packages-19.07/g; }'  /etc/opkg/distfeeds.conf
sed -i '/openwrt_routing/ { s/snapshots\/packages/releases\/packages-19.07/g; }'   /etc/opkg/distfeeds.conf
sed -i '/openwrt_telephony/ { s/snapshots\/packages/releases\/packages-19.07/g; }' /etc/opkg/distfeeds.conf
sed -i '/natelol/d'                                                                /etc/opkg/distfeeds.conf
sed -i 's,downloads.openwrt.org,mirrors.cloud.tencent.com/lede,g'                  /etc/opkg/distfeeds.conf
#uhttpd
uci set uhttpd.main.rfc1918_filter='0'
uci set uhttpd.main.redirect_https='0'
uci commit uhttpd
/etc/init.d/uhttpd restart
#firewall
uci set firewall.@defaults[0].fullcone='1'
uci commit firewall
#dropbear
uci set dropbear.@dropbear[0].Interface='lan'
uci commit dropbear
/etc/init.d/dropbear restart
#upnp
uci set upnpd.config.enabled='1'
uci del upnpd.config.enable_upnp
uci del upnpd.config.enable_natpmp
uci set upnpd.config.external_iface='wan'
uci commit upnpd
#openssl.cnf
sed -i 's,#devcrypto,devcrypto,g' /etc/ssl/openssl.cnf
sed -i 's,#USE_SOFTDRIVERS = 2,USE_SOFTDRIVERS = 1,g' /etc/ssl/openssl.cnf
#dnsmasq
sed -i '/log-facility/d' /etc/dnsmasq.conf
echo 'log-facility=/dev/null' >> /etc/dnsmasq.conf
#packet_steering
uci set network.globals.packet_steering='1'
uci commit network
#symlink for ip command
ln -sf /sbin/ip /usr/bin/ip
#opkg hold patched packages
opkg flag hold luci-app-ddns
opkg flag hold luci-i18n-ddns-zh-cn
opkg flag hold ddns-scripts
opkg flag hold ddns-scripts_cloudflare.com-v4
opkg flag hold luci-app-firewall
opkg flag hold firewall
opkg flag hold dnsmasq-full
#luci cache
rm -rf /tmp/luci-modulecache
rm  -f /tmp/luci-indexcache
exit 0
